version: '3'

services:
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./backend
        volumes:
            - /app/node_modules
            - ./backend:/app
        ports:
            - '3001:3001'
        restart: on-failure
        container_name: api
        image: jgupchurch/mangrove-api-dev


    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
        ports:
            - '3000:3000'
        restart: on-failure
        container_name: client
        image: jgupchurch/mangrove-client-dev

